export const subjectList = [
  "Afrikaans",
  "English",
  "Ndebele",
  "Northern Sotho",
  "Southern Sotho",
  "Swazi",
  "Tsonga",
  "Tswana",
  "Venda",
  "Xhosa",
  "Zulu",
  "Accounting",
  "Agricultural Management Practices",
  "Agricultural Sciences",
  "Agricultural Technology",
  "Business Studies",
  "Civil Technology",
  "Computer Applications Technology",
  "Consumer Studies",
  "Dance Studies",
  "Design",
  "Dramatic Arts",
  "Economics",
  "Electrical Technology",
  "Engineering Graphics & Design",
  "Geography",
  "History",
  "Hospitality Studies",
  "Information Technology",
  "Life Sciences",
  "Life Orientation",
  "Mechanical Technology",
  "Music",
  "Mathematics",
  "Mathematical Literacy",
  "Physical Science",
  "Religion Studies",
  "Second Additional Language",
  "Third Additional Language",
  "Tourism",
  "Technical Mathematics",
  "Visual Arts",
];
export const ratingScale = [
  { description: "Outstanding", percentage: "80_100" },
  { description: "Meritorious", percentage: "70_79" },
  { description: "Substantial", percentage: "60_69" },
  { description: "Adequate", percentage: "50_59" },
  { description: "Moderate", percentage: "40_49" },
  { description: "Elementary", percentage: "30_39" },
  { description: "Not achieved", percentage: "0_29" },
];
